export const AUTHENTICATION = 'AUHENTICATION';
export const LOAD_AUTH_DATA = 'LOAD_AUTH_DATA';
export const POST_REQUEST = 'POST_REQUEST';
export const PUT_REQUEST = 'PUT_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DATA_FETCHING = 'DATA_FETCHING';
export const DATA_FETCHING_ERR = 'DATA_FETCHING_ERR';
export const LOGIN = 'LOGIN';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const LOGOUT = 'LOGOUT';
export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
export const SET_LOGIN_ERROR_FALSE = 'SET_LOGIN_ERROR_FALSE';
export const SET_SALE_CART = 'SET_SALE_CART';
export const SET_SALE_CUSTOMER = 'SET_SALE_CUSTOMER';
export const SET_SALE_PAYMENT_METHOD = 'SET_SALE_PAYMENT_METHOD';

export const SET_RECEIVE_CART = 'SET_RECEIVE_CART';
export const SET_RECEIVE_SUPPLIER = 'SET_RECEIVE_SUPPLIER';
export const SET_RECEIVE_PAYMENT_METHOD = 'SET_RECEIVE_PAYMENT_METHOD';

export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_IS_BRANDED = 'SET_IS_BRANDED';

export const SET_SUPPLIER_LIST = 'SET_SUPPLIER_LIST';
export const SET_ALL_SUPPLIER_LIST = 'SET_ALL_SUPPLIER_LIST';

export const SET_ITEM_LIST = 'SET_ITEM_LIST';
export const SET_FORMATTED_ITEM_LIST = 'SET_FORMATTED_ITEM_LIST';

export const SET_ALL_BRAND_LIST = 'SET_ALL_BRAND_LIST';

export const SET_ALL_STOCK_LIST = 'SET_ALL_STOCK_LIST';
